### PR TITLE
Update to v2.0.3

### PR DESCRIPTION
**Pull request by ErikPartridge**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This updates to v2.0.3 with fixes for the dependencies.

<code>@<space/>conda-forge-admin please rerender</code>

### CODE REVIEW

**Comment by ErikPartridge** [comment]
`@conda-forge-admin, please rerender`

**Comment by proinsias** [comment]
@conda-forge-admin, please rerender

**Comment by sbrugman** [comment]
@conda-forge-admin, please rerender

**Comment by ErikPartridge** [comment]
I manually re-rendered it and added those to the branch using the cli. I'm not sure why it's failing to push, I do have the box checked. In any case, should still be okay given that it has been rendered offline.

**Pull request closed without merging**
